import '../logic/task.dart';

class TasksList
{
  static List<Task> tasks =
  [
    new Task('👶', 'Be born'),
    new Task('🚶‍', 'Learn to walk'),
    new Task('📣', 'Say first words'),
    new Task('👨‍🏫', 'Learn to read'),
    new Task('🤗', 'Make a friend'),
    new Task('📗', 'Read a book'),
    new Task('🏊‍', 'Learn to swim'),
    new Task('🏫', 'Finish elementary school'),
    new Task('⚽', 'Play a sport'),
    new Task('🛫', 'Fly in a plane'),
    new Task('🛥️', 'Ride in a boat'),
    new Task('🚆', 'Ride in a train'),
    new Task('🚁', 'Ride in a helicopter'),
    new Task('🌊', 'See the ocean'),
    new Task('❄️', 'See some snow'),
    new Task('☃️', 'Make a snowman'),
    new Task('❄️☃️', 'Have a snowball fight'),
    new Task('🎢', 'Ride a rollercoaster'),
    new Task('🏕️', 'Go camping'),
    new Task('🏫', 'Finish middle school'),
    new Task('🎶', 'Go to a concert'),
    new Task('🎻', 'Learn to play an instrument'),
    new Task('💳', 'Open a bank account'),
    new Task('🚘', 'Drive'),
    new Task('🗾', 'Visit another country'),
    new Task('🗺️', 'Go on a roadtrip'),
    new Task('🎤', 'Give a public speech'),
    new Task('🏫', 'Graduate high school'),
    new Task('🌐', 'Learn another language'),
    new Task('📷', 'Get an autograph from an idol'),
    new Task('😩', 'Make a terrible mistake'),
    new Task('🏆', 'Win a trophy'),
    new Task('⛰️', 'Climb a mountain'),
    new Task('🎽', 'Run a marathon'),
    new Task('🍳', 'Cook your first meal'),
    new Task('🔥', 'Burn a meal'),
    new Task('🔦', 'Explore a cave'),
    new Task('🌋', 'See a volcano'),
    new Task('🎓', 'Graduate college'),
    new Task('🌷', 'Plant a garden'),
    new Task('💕', 'Have a long relationship'),
    new Task('💔', 'Get a broken heart'),
    new Task('🏢🙍‍', 'Prepare a job interview'),
    new Task('🏢🍾', 'Get a job'),
    new Task('☝️', 'Get promoted'),
    new Task('💵', 'Receive your first paycheck'),
    new Task('🔥', 'Get fired'),
    new Task('📰', 'Get in the news'),
    new Task('🗳️', 'Vote in an election'),
    new Task('🏠', 'Buy a house'),
    new Task('👰', 'Get married'),
    new Task('👶', 'Have a kid'),
    new Task('👨‍👩‍👧‍👦', 'Have multiple kids'),
    new Task('🚶‍', 'Teach your kids to walk'),
    new Task('📣', 'Teach your kid to talk'),
    new Task('🎓', 'Watch your kid graduate'),
    new Task('👰', 'Watch your kid get married'),
    new Task('👴', 'Become a grandparent'),
    new Task('🏖️', 'Retire'),
    new Task('📔', 'Tell your grandkid a story'),
    new Task('🌑', 'See a solar eclipse'),
    new Task('🌎', 'Travel the world'),
    new Task('🎂', 'Turn 100 years old'),
    //new Task('✔️', 'Complete Life Checklist'),
  ];
}